// <auto-generated />
using BreakDown_Assistance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BreakDown_Assistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191225172708_BreakDownDatabase")]
    partial class BreakDownDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BreakDown_Assistance.Models.Mechanics", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("availability")
                        .IsRequired()
                        .HasColumnName("availability")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("contact_Number")
                        .HasColumnName("contact_Number")
                        .HasColumnType("int");

                    b.Property<double>("latitude")
                        .HasColumnName("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnName("longitude")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Mechanics");
                });

            modelBuilder.Entity("BreakDown_Assistance.Models.Request", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("latitude")
                        .HasColumnName("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnName("longitude")
                        .HasColumnType("float");

                    b.Property<int>("mechanic_ID")
                        .HasColumnName("mechanic_ID")
                        .HasColumnType("int");

                    b.Property<string>("vehcileType")
                        .IsRequired()
                        .HasColumnName("vehcileType")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("mechanic_ID");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("BreakDown_Assistance.Models.Request", b =>
                {
                    b.HasOne("BreakDown_Assistance.Models.Mechanics", "mehanics")
                        .WithMany("requests")
                        .HasForeignKey("mechanic_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
